users:
  secret-key: ${SECRET:188f181e-35f9-4913-9c8a-13e62ed588ac}
keycloak:
  uri: ${KEYCLOAK:localhost}
spring:
  application:
    name: Users
  config:
    import: optional:configserver:http://${ConfigService:localhost}:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    schemaName: ${spring.application.name}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:Cinema}?currentSchema=public&stringtype=unspecified&ApplicationName=${spring.application.name}&reWriteBatchedInserts=true
    username: ${DBUSER:cinema}
    password: ${DBPASSWORD:cinema}
    # if true initializes db using sql scripts
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
      hbm2dll:
        create_namespaces: true
        default_schema: adapterborder
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYLOCAK_URI:http://localhost:28080}/auth/realms/cinema/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8887/eureka}
  instance:
    preferIpAddress: true


