openapi: 3.0.0
info:
  version: 1.0.0
  title: cinema-hall
paths:
  /:
    get:
      summary: Get cinemahalls for worker
      operationId: getCinemaHallsForWorker
      responses:
        '200':
          description: 'cinemaHalls for cinema'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CinemaHall'

  /{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
          format: int64
        required: true
    get:
      summary: Get cinemahalls by cinemaId
      operationId: getCinemaHalls
      responses:
        '200':
          description: 'cinemaHalls for cinema'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CinemaHall'
    post:
      operationId: createCinemaHall
      description: creates cinemaHall
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CinemaHallRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaHall'
  /details/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
          format: int64
        required: true
    get:
      summary: Get cinemahalls by cinemaId
      operationId: getCinemaHall
      responses:
        '200':
          description: 'cinemaHalls detail'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CinemaHall'
    delete:
      summary: delete cinema hall
      operationId: deleteCinemaHall
      responses:
        '200':
          description: 'cinemaHalls detail'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaHall'
  /details/{id}/{state}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
          format: int64
        required: true
      - name: state
        in: path
        schema:
          $ref: '#/components/schemas/SeatState'
        required: true
    put:
      summary: change seat state
      operationId: changeSeatState
      responses:
        '200':
          description: 'change seat state'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seat'

components:
  schemas:
    CinemaHallRequest:
      type: object
      properties:
        name:
          type: string
        xRows:
          type: integer
          format: int32
        yRows:
          type: integer
          format: int32
    CinemaHall:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        cinemaId:
          type: integer
          format: int64
        seats:
          type: array
          items:
            $ref: '#/components/schemas/Seat'
    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        row:
          type: integer
          format: int32
        column:
          type: integer
          format: int32
        seatState:
          $ref: '#/components/schemas/SeatState'
    SeatState:
      type: string
      enum:
        - AVAILABLE
        - UNAVAILABLE
        - MAINTANCE_SCHEDULED