
spring:
  application:
    name: Schedule
  config:
    import: optional:configserver:http://${ConfigService:localhost}:8888
  datasource:
    spring:
      jpa:
        properties:
          hibernate:
            default_schema=schema-name: schedule
    driver-class-name: org.postgresql.Driver
    schemaName: ${spring.application.name}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:Cinema}?currentSchema=schedule&createDatabaseIfNotExist=true
    username: ${DBUSER:cinema}
    password: ${DBPASSWORD:cinema}
    # if true initializes db using sql scripts
    initialize: false
  jpa:
    hibernate:
      ddl-auto: create-drop
      hbm2dll:
        create_namespaces: true
        default_schema: adapterborder
    properties:
      javax:
        persistence:
          create-database-schemas: true
          schema-generation:
            database:
              action: create
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:28080/auth/realms/cinema/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8887/eureka}
  instance:
    preferIpAddress: true
server:
  port: 0

